name: redux_machine
description: Redux Store implementation which can also be used as a state machine.
version: 1.0.0-rc.3
homepage: https://github.com/pulyaevskiy/redux-machine
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dev_dependencies:
  test: ^1.0.0
