name: redux_machine
description: State machine with Redux flow
version: 0.0.1
homepage: https://github.com/pulyaevskiy/redux-machine
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.24.2 <2.0.0'

dev_dependencies:
  test: ^0.12.0
