name: redux_machine
description: Redux State Machine and Store with no side-effects.
version: 1.0.0-dev.1.0
homepage: https://github.com/pulyaevskiy/redux-machine
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=2.0.0-dev <3.0.0'

dev_dependencies:
  test: ^0.12.0
